config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  # get 'home/zipcode'

  post "zipcode", to: 'home#zipcode'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'
    @url = "http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=92154&distance=0&API_KEY=F0D990AA-C672-4CBC-BF32-39F1CF27C931"
    @uri = URI(@url)

    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)

    # check for empty request result
    if @output.empty?
      @final_ouput = "Error, zip code not valid."
    else
      @final_ouput = @output[0]["AQI"]
    end

    if @final_ouput == "Error, zip code not valid."
      @api_color = "silver"
      @api_message = "No description for this request."
    elsif @final_ouput <= 50
      @api_color = "green"
      @api_message = "Good (0 - 50) Air quality is considered satisfactory, and air pollution poses little or no risk."
    elsif @final_ouput >= 51 && @final_ouput <= 100
      @api_color = "yellow"
      @api_message = "Moderate (51 - 100) Air quality is acceptable."
    elsif @final_ouput >= 101 && @final_ouput <= 150
      @api_color = "orange"
      @api_message = "Unhealthy for Sensitive Groups (101 - 150)"
    elsif @final_ouput >= 151 && @final_ouput <= 200
      @api_color = "red"
      @api_message = "Unhealthy (151 - 200)"
    elsif @final_ouput >= 201 && @final_ouput <= 300
      @api_color = "purple"
      @api_message = "Very Unhealthy (201 - 300)"
    else
      @api_color = "maroon"
      @api_message = "Hazardous (301 - 500)
Health warnings of emergency conditions. The entire population is more likely to be affected."
    end
  end

  def zipcode
    @zip_query = params[:zipcode]
    if params[:zipcode] == ""
      @zip_query = "Hey you forgot to type the zipcode"
    elsif params[:zipcode]

        require 'net/http'
        require 'json'
        @url = 'http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=' + @zip_query + '&distance=0&API_KEY=F0D990AA-C672-4CBC-BF32-39F1CF27C931'
        @uri = URI(@url)

        @response = Net::HTTP.get(@uri)
        @output = JSON.parse(@response)

        # check for empty request result
        if @output.empty?
          @final_ouput = "Error, zip code not valid."
        else
          @final_ouput = @output[0]["AQI"]
        end

        if @final_ouput == "Error, zip code not valid."
          @api_color = "silver"
          @api_message = "No description for this request."
        elsif @final_ouput <= 50
          @api_color = "green"
          @api_message = "Good (0 - 50) Air quality is considered satisfactory, and air pollution poses little or no risk."
        elsif @final_ouput >= 51 && @final_ouput <= 100
          @api_color = "yellow"
          @api_message = "Moderate (51 - 100) Air quality is acceptable."
        elsif @final_ouput >= 101 && @final_ouput <= 150
          @api_color = "orange"
          @api_message = "Unhealthy for Sensitive Groups (101 - 150)"
        elsif @final_ouput >= 151 && @final_ouput <= 200
          @api_color = "red"
          @api_message = "Unhealthy (151 - 200)"
        elsif @final_ouput >= 201 && @final_ouput <= 300
          @api_color = "purple"
          @api_message = "Very Unhealthy (201 - 300)"
        else
          @api_color = "maroon"
          @api_message = "Hazardous (301 - 500)
    Health warnings of emergency conditions. The entire population is more likely to be affected."
        end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Ozone App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      </ul>
      <%= form_tag zipcode_path, :method => 'POST' do %>
      <div class="d-flex form-inline my-2 my-lg-0">
        <%= text_field_tag 'zipcode', nil, placeholder: "Search Zipcode", class: "form-control mr-sm-2" %>
        <%= submit_tag 'Search', class: 'btn btn-outline-secondary my-2 my-sm-0' %>
      </div>
    <% end %>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="jumbotron <%= @api_color %> ">
  <h1 class="display-4"><%= @final_ouput %></h1>
  <p class="lead">This is the current ozone quality readout for my neighborhood in <%= @final_ouput.nil? ? @output[0]["ReportingArea"] : "No City found." %>.</p>
  <hr class="my-4">
  <p> <%= @api_message  %> </p>
  <br>
</div>

<br>

app/views/home/zipcode.html.erb
<div class="jumbotron <%= @api_color %> ">
  <h1 class="display-4"><%= @final_ouput %></h1>
  <p class="lead">This is the current ozone quality readout for my neighborhood in <%= @zip_query %> zipcode.</p>
  <hr class="my-4">
  <p> <%= @api_message  %> </p>
  <br>
</div>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OzoneWebApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "home/navbar"  %>
    <div class="container">
      <br>
      <%= yield %>
    </div>
  </body>
</html>